[FEATURE] Add support for multiple cache implementations, separating result, query and metadata caching.
laravel-doctrine/orm pull request #205
Opened 2017-01-19 21:41 UTC by BrandonLegault

This PR adds the ability to configure a different cache driver for each of metadata, result and query caching through the `doctrine.php` config file `'cache'` array.

### Changes proposed in this pull request:

The current cache array format is as follows:

```
'cache'            => [
    'default'      => env('DOCTRINE_CACHE', 'array'),
    'namespace'    => null,
    'second_level' => false,
]
```

This branch introduces this format:

  ```
    'cache' => [
        'second_level'     => false,
        'default'          => env('DOCTRINE_CACHE', 'array'),
        'namespace'        => null,
        'metadata'         => [
            'type'         => 'file',
            'namespace'    => null,
        ],
        'query'            => [
            'type'         => 'redis',
            'namespace'    => null,
        ],
        'result'           => [
            'type'         => 'array',
            'namespace'    => null,
        ],
    ],
```
The configuration is done by calling `\Doctrine\ORM\Configuration->set[Result|Query|Metadata]CacheImpl` after reading the values from the config.

The `default` cache array entries remain the same to ensure backwards compatibility. If any of the metadata, result or query entries are missing from the configuration then they will take whichever the default entry is. The default entry is also mirrored/stored directly in code in case it's accidentally deleted from the configuration.

2017-01-25 19:15 UTC, patrickbrouwers requested changes
Can you also update the config file with the new structure, thanks!
It would be good to provide env variables for the 3 drivers as well. They can all 3 default to the DOCTRINE_CACHE env variable.

2017-01-25 19:15 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +    private function applyNamedCacheConfiguration($cacheName)
Docblocks

2017-01-25 19:15 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +        $driverType = $this->config->get('doctrine.cache.' . $cacheName . '.type', $defaultDriver);
`type` should be named `driver`

2017-01-25 19:33 UTC, BrandonLegault commented
I added the requested changes... I also rebased from 1.2 to keep my branch up to date. I'd already made the changes before I saw the DOCTRINE_CACHE env variable comment. I made them take on new env variables. Do you want me to change that?

2017-01-25 19:39 UTC, patrickbrouwers requested changes

2017-01-25 19:39 UTC, patrickbrouwers commented on config/doctrine.php
> +        'default'          => 'array',
'default'          => env('DOCTRINE_CACHE', 'array'),

2017-01-25 19:39 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +        $driver = $this->config->get('doctrine.cache.' . $cacheName . '.driver', $defaultDriver);
$cache = $this->cache->driver($driver);

if ($namespace = $this->config->get('doctrine.cache.' . $cacheName . '.namespace', $defaultNamespace)) {
    $cache->setNamespace($namespace);
}

return $cache;

2017-01-25 19:39 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +        $defaultDriver    = $this->config->get('doctrine.cache.default', $this->defaultCache['type']);
Replace `$this->defaultCache['type']` by `'array'`
Remove `$this->defaultCache['namespace']`

2017-01-25 19:39 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +    private $defaultCache = [
Not necessary

2017-01-25 19:41 UTC, patrickbrouwers commented
>  I made them take on new env variables. Do you want me to change that?

No it's fine.

2017-01-29 12:04 UTC, patrickbrouwers approved these changes

2017-01-29 12:04 UTC, merged