[FEATURE] Add the routes substitute bindings middleware for doctrine entities
laravel-doctrine/orm pull request #207
Opened 2017-01-24 23:07 UTC by HDsign

#187 

I've added the SubstituteBindings middleware which replaces the laravel middleware.
The entity manager will be fetched from the registry class.

I will try to add tests asap!

### Changes proposed in this pull request:
- Added SubstituteBindings middleware.
- Added Illuminate/routing 5.2.*|5.4.* to composer.json

2017-01-25 17:36 UTC, guiwoda commented on src/Middleware/SubstituteBindings.php
> +class SubstituteBindings extends IllumintateSubstituteBindings
@HDsign this is confusing, I don't see any calls to `parent` other than the constructor. Is it really necessary to extend Eloquent's middleware?

2017-01-25 17:44 UTC, HDsign commented on src/Middleware/SubstituteBindings.php
> +class SubstituteBindings extends IllumintateSubstituteBindings
Well in the handle method the parent router property is called to add the eloquent substitute bindings. This allows the user to get rid of the default SubstituteBindings middleware. Other than that it is not necessary to extend the original middleware.

I guess we could just have both middleware and just add this middleware to add doctrine support.

2017-01-25 17:52 UTC, patrickbrouwers requested changes

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +     * @param  string                                     $class
string|object

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +        if (is_object($class)) {
In which case could this be an object?

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +class SubstituteBindings extends IllumintateSubstituteBindings
Don't think extension is needed here. Best to define the router property in this class.

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +                $entity = $entityManager->find($class, $parameters[$parameter->name]);
How does Eloquent behave in this case? Do they allow null? Or do they thrown an exception if the entity does not exist?

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +                $entity = $entityManager->find($class, $parameters[$parameter->name]);
Seems they have something in place for both situations.
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/Router.php#L805

Can you try and make it behave it the same way as Eloquent does.

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +    protected function substituteImplicitBindings($route)
Typehint Route $route

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +     * @return void
Ommit @return void

2017-01-25 17:52 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +     * @param  string | Closure       $uses
string|callable

2017-01-25 19:12 UTC, patrickbrouwers requested changes

2017-01-25 19:12 UTC, patrickbrouwers commented on src/Middleware/SubstituteBindings.php
> +
I think the call to `$this->router->substituteBindings($request->route())` could have stayed.

2017-01-26 11:41 UTC, Evertt commented on src/Middleware/SubstituteBindings.php
> +        return $parameters = (new ReflectionFunction($uses))->getParameters();
Why is the `$parameters = ` here? Surely after this function returns (which is on this exact line) the variable `$parameters` will be destroyed right? So what is its purpose on this line?

2017-01-26 12:16 UTC, HDsign commented on src/Middleware/SubstituteBindings.php
> +        return $parameters = (new ReflectionFunction($uses))->getParameters();
Hmm, there's absolutely no reason whatsoever 😄 I'll fix it.

2017-01-26 17:35 UTC, patrickbrouwers commented
> I will try to add tests asap!
Any ETA on this?

2017-01-26 17:49 UTC, HDsign commented
I'll start on these tonight, try to finish them this weekend 👍

2017-01-26 17:49 UTC, patrickbrouwers commented
Great, thanks!

2017-01-26 20:27 UTC, HDsign commented
Guess I've writen them already 😄

2017-01-26 22:45 UTC, patrickbrouwers commented
Looking good! Will have a last look at it tomorrow.

2017-01-29 12:04 UTC, patrickbrouwers approved these changes

2017-01-29 12:04 UTC, merged