Fixing default caching bug introduced from #205
laravel-doctrine/orm pull request #211
Opened 2017-02-17 16:49 UTC by ragboyjr

If you have memcached or redis extensions installed
doctrine will try to automatically connect to one of them
if no cache paramter is set when dev mode is off. Defaulting
to ArrayCache to prevent that behavior from occuring.

Signed-off-by: RJ Garcia <rj@bighead.net>

Please prefix your pull request with one of the following: [FIX] [FEATURE].

### Changes proposed in this pull request:
-
-
-

2017-02-19 23:35 UTC, patrickbrouwers requested changes

2017-02-19 23:35 UTC, patrickbrouwers commented on src/EntityManagerFactory.php
> +            new ArrayCache()
It's probably best to get the actual default cache driver then:

$defaultDriver    = $this->config->get('doctrine.cache.default', 'array');
$this->cache->driver($driver);

2017-02-20 02:33 UTC, ragboyjr commented
@patrickbrouwers no problem, can you check now?

2017-02-21 02:39 UTC, nghiaminhle commented
i have the same problem. Please add this line into EntityFactoryManager:
  /**
     * @param array $settings
     *
     * @return EntityManagerInterface
     */
    public function create(array $settings = [])
    {
        $configuration = $this->setup->createConfiguration(
            array_get($settings, 'dev', false),
            array_get($settings, 'proxies.path'),
            $this->cache->driver()
        );
----------

2017-02-21 11:57 UTC, merged