[FEATURE] Master/slave connection support.
laravel-doctrine/orm pull request #214
Opened 2017-03-06 13:04 UTC by Zylius

### Changes proposed in this pull request:
- Add support for master slave configuration.

2017-03-06 17:56 UTC, patrickbrouwers commented
Can you add some more information to the PR?
E.g. does it have breaking changes for using the current state of the config file?

2017-03-06 18:10 UTC, guiwoda requested changes

2017-03-06 18:10 UTC, guiwoda commented on src/EntityManagerFactory.php
> +        if (($key = array_search(0, array_map('count', $slaves))) && $key !== false) {
isn't `$key !== false` redundant here? if its `false`, first condition fails.
Search could return position 0, which would be false-_ish_ here as well, right?

2017-03-06 18:10 UTC, guiwoda commented on tests/Configuration/Connections/MasterSlaveConnectionTest.php
> +        $this->assertEquals(
I like how you used dataProvider to reuse this case multiple times, but I find it a bit hard to maintain in this current form.
I wouldn't know where to modify each expectation for each setting.

Maybe refactor each case into its own method, then do something like:

```
public function getMasterSlaveConnectionData()
{
    return [
        $this->dummyBaseSettings(), $this->dummyConfig(), $this->dummyExpectations(),
        $this->oracleBaseSettings(), $this->oracleConfig(), $this->oracleExpectations(),
}
```

Or something along those lines?

2017-03-06 18:10 UTC, guiwoda commented on tests/EntityManagerFactoryTest.php
> +
Remove empty line between use statements.

2017-03-06 18:10 UTC, guiwoda commented on tests/EntityManagerFactoryTest.php
> +    public function getTestMasterSlaveConnectionData()
Same as comment :point_up:

2017-03-07 10:14 UTC, maxbrokman reviewed
Is a duplicate of #157 ?

2017-03-07 10:14 UTC, maxbrokman commented on src/EntityManagerFactory.php
> +        if (($key = array_search(0, array_map('count', $slaves))) && $key !== false) {
yeah this seem like it's trying to be too clever by half and will fail if the first config (position 0) is empty, poc here https://3v4l.org/N8gnk There doesn't seem to be any tests for this?

A lot of this could be replaced with

```
array_map(function($config){
    if (!is_array($config)) {
        //...
    }

    if (!count($config)) {
          //...
    }
}, $slaves);
```

only one loop, probably less buggy.

2017-03-07 10:14 UTC, maxbrokman commented on tests/EntityManagerFactoryTest.php
> +            "Parameter 'read' config no. 2 is empty."
consider adding a test for the bug when read config 0 is empty

2017-03-07 12:08 UTC, Zylius commented on src/EntityManagerFactory.php
> +        if (($key = array_search(0, array_map('count', $slaves))) && $key !== false) {
That's correct, it's faulty. Will remove the second check and add a test case for it.

2017-03-07 13:41 UTC, Zylius commented
Updated it according to comments. I'm fully aware this is a duplicate of two other PRs but hopefully since there are so many PRs for this issue we'll get one in laravel doctrine and this PR will be the one getting merged.

2017-03-07 13:44 UTC, guiwoda approved these changes

2017-03-28 23:07 UTC, patrickbrouwers commented
Can you add an example config to `/config`. This doesn't have to get published, but would be a good reference point for anybody wanting to use master-slave. Also a PR to our Docs repo would be very helpful.

2017-03-29 06:52 UTC, Zylius commented
I don't know why you guys want to add sample documentation for laravels configuration file in your ORM repo but I'll do it. Also, you can find actual documentation for this on the [laravel web site].(https://laravel.com/docs/5.4/database#read-and-write-connections)

2017-03-29 07:09 UTC, Zylius commented
And here is the docs PR https://github.com/laravel-doctrine/docs/pull/67.

2017-03-29 16:14 UTC, kpicaza commented
Sorry, this pull request will be merged in future versions of package? 

It can be very powerful feature for most of big projects.

Thanks

2017-03-29 19:52 UTC, patrickbrouwers commented
@kpicaza yes, if it passes my functional tests I'll merge it.

2017-04-11 16:29 UTC, kpicaza commented
Can i help you on this issue improving tests or doing something that is needed?

2017-04-12 10:42 UTC, Zylius commented
So are you guys actually planning to merge this or just ignore it for the next six months and close it like the other PRs?

I don't really care, but it seems like the community really wants it, and it doesn't look like anything is failing because of this new feature.

2017-04-12 11:36 UTC, guiwoda commented
This PR was opened a month ago, not six. And we've shown interest in it. 
Mind your attitude, please. We appreciate your help, but just as you, we have other responsibilities outside open source. This will be reviewed and merged when we can spare the time to do so, in the meantime, people can force their dependencies to the fork if they really need it, or implement master / slave outside app, which can also be done.

2017-04-12 12:24 UTC, Zylius commented
There must've been some misunderstanding, I was talking about the older PRs being open for six months and being closed.
Yeah, I've done the master/slave inside app thing. Just trying to help out the community.
Anyways, I appreciate your efforts in trying to make laravel a better framework!

2017-04-12 12:59 UTC, guiwoda commented
I think you may be confusing projects: we don't have any history of closing six-month-old PRs.

I've fixed Travis configuration, now 1.3 is running (and passing) all tests. Please rebase your fork and check that tests also pass in it.

2017-04-12 13:31 UTC, Zylius commented
Done ;)

2017-04-12 15:02 UTC, guiwoda requested changes
Some more suggestions, I think it looks pretty good overall. Would merge as soon as this is ready!

2017-04-12 15:02 UTC, guiwoda commented on config/read_write_database_sample.php
> +    'default' => env('DB_CONNECTION', 'auth'),
Having an invalid default here may be confusing for users.

2017-04-12 15:02 UTC, guiwoda commented on config/read_write_database_sample.php
> +<?php
Do we want a sample in code? I believe having updated docs with sample in docs will have better visibility.
Also, if syntax matches what Laravel documents, then we don't really need this at all.

2017-04-12 15:02 UTC, guiwoda commented on src/EntityManagerFactory.php
> +        if ($this->isMasterSlaveConfigured($driver) && $this->hasValidMasterSlaveConfig($driver)) {
Refactor into:

```php
if ($this->isMasterSlaveConfigured()) {
    $this->validateMasterSlaveConfig($driver);

    $connection = (new ...);
}
```

2017-04-12 15:02 UTC, guiwoda commented on src/EntityManagerFactory.php
> +        return true;
By suggested refactor, this method does not need a return value

2017-04-12 15:03 UTC, guiwoda commented on config/read_write_database_sample.php
> +<?php
This question is meant for @patrickbrouwers actually, as he suggested adding it :smile:

2017-04-12 22:18 UTC, patrickbrouwers commented on config/read_write_database_sample.php
> +<?php
Yes can be removed, I didn't understand at first it was the same syntax as the laravel docs.

2017-04-13 06:22 UTC, Zylius commented
Done.

2017-04-13 13:02 UTC, guiwoda approved these changes

2017-04-13 13:03 UTC, guiwoda commented
I'm :+1: with this!
Shoud we merge, @patrickbrouwers ?

2017-04-24 20:02 UTC, patrickbrouwers approved these changes

2017-04-24 20:02 UTC, merged