[FIX] Presence verifier on lumen
laravel-doctrine/orm pull request #215
Opened 2017-03-09 23:21 UTC by Lidbetter

### Changes proposed in this pull request:
- Unbind default framework binding implementations of 'validator' (if wanting to use doctrine presence)
- Tweak binding of  `PresenceVerifierProvider` to account for the removal of the default  'validator' binding (if wanting to use doctrine presence)
- Ensure the default implementation of `ValidationServiceProvider` has a db instance to use when checking to see if it should set the presence verifier (when using the default presence)

2017-03-09 23:22 UTC, Lidbetter commented
Fixes #202

2017-03-21 17:07 UTC, rgwsk65 commented
Is there a chance of merge this PR?

2017-03-28 23:16 UTC, patrickbrouwers requested changes

2017-03-28 23:16 UTC, patrickbrouwers commented on src/Validation/PresenceVerifierProvider.php
> +    protected function registerValidationFactory()
Is it necessary to redeclare this if we are extending `ValidationServiceProvider` ?

2017-04-09 18:28 UTC, Lidbetter commented on src/Validation/PresenceVerifierProvider.php
> +    protected function registerValidationFactory()
Yes, the default implementation checks for different unrelated conditions before calling `$validator->setPresenceVerifier`

2017-04-24 20:00 UTC, patrickbrouwers approved these changes

2017-04-24 20:00 UTC, merged