[FEATURE] Add ability to provide different folders for Entity Factories via doctrine.php config
laravel-doctrine/orm pull request #228
Opened 2017-04-12 15:33 UTC by Shandur

### Changes proposed in this pull request:
- Using doctrine.php config file user can use his own Entity Factory folders. 

_Reason:_
I was stuck with a problem: I'm developing an application using modular approach. Each module has its own entities and its own factories for them. But I couldn't run the factories because of hard-coded folder that leads to 'database/factories' in the project root.

Thanks!

2017-04-12 20:49 UTC, patrickbrouwers requested changes
Nice idea :)

2017-04-12 20:49 UTC, patrickbrouwers commented on config/doctrine.php
> +            // 'Modules/User/Database/Factory',
Can you add `database_path('factories')` as default here.
Also probably better to set the example to `base_path('Modules/...')` ?

2017-04-12 20:49 UTC, patrickbrouwers commented on src/Testing/Factory.php
> +        foreach ((array)$pathToFactories as $factoryDir) {
Code style: space behind `(array)`

2017-04-12 21:02 UTC, guiwoda commented
My 2c: Don't use scripts if you want to modularize. Use ServiceProviders.

Sample:

```php
use LaravelDoctrine\ORM\Testing\Factory as EntityFactory;

class SomeModuleServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->afterResolving(EntityFactory::class, function (EntityFactory $factory) {
            $factory->define(SomeEntity::class, function ($faker) {
                // your definition here :-)
            });
        });
    }
}
```

2017-04-12 21:04 UTC, patrickbrouwers commented
Actually have to agree with @guiwoda. Sounds indeed a better idea to modularize :)

2017-04-13 06:39 UTC, Shandur commented
@guiwoda @patrickbrouwers Probably you're right about using service providers for adding entity factories. But if you have about 10 or more entities and you need factories for them, it's not comfortable inject them into service provider. It could be better to add extra folders to doctrine config via service provider (while register) instead of writing them directly into the file :)

2017-04-13 06:46 UTC, Shandur commented on config/doctrine.php
> +            // 'Modules/User/Database/Factory',
@patrickbrouwers sure, thanks :) it looks better

2017-04-13 12:59 UTC, guiwoda commented
Then do something like...

```php
use LaravelDoctrine\ORM\Testing\Factory as EntityFactory;

class SomeModuleServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->afterResolving(EntityFactory::class, function (EntityFactory $factory) {
            foreach ($this->getFactoryFolders() as $path) {
                require $path;
            }
        });
    }
}
```

2017-04-13 13:00 UTC, guiwoda commented
I'm sorry but your use case is not something I'd want to generalize in the package, and if it were, I don't agree with what you're proposing either. I appreciate your intention to contribute, but I have to say I don't think this needs to be merged.

2017-04-13 14:56 UTC, Shandur commented
@guiwoda Ok, it's up to you, thanks for you reply :)

2017-04-24 19:59 UTC, patrickbrouwers commented
Closing this in favour of registering it through the service provider

2017-04-24 19:59 UTC, closed without merging