[FEATURE] Adds debugbar key to doctrine collector.
laravel-doctrine/orm pull request #241
Opened 2017-06-12 15:53 UTC by zquintana

This PR is for the proposal in https://github.com/laravel-doctrine/orm/issues/237. It adds config for the doctrine debugbar widget name. It was mentioned to use the `env`, but I added it to the configs because the use of `env` outside of configs is deprecated in laravel 5.2+ and it's use doesn't work when configs are cached.

The new config name is `debugbar_widget_key` and it defaults to the current value. Setting it in config will allow the eloquent debugbar to show with the doctrine debugbar.

2017-06-13 12:35 UTC, guiwoda requested changes

2017-06-13 12:35 UTC, guiwoda commented on src/Loggers/Debugbar/DoctrineCollector.php
> +    protected $name;
I'd stay consistent with the `key` keyword here as well.

2017-06-13 12:36 UTC, guiwoda commented
Please fix the tests as well

2017-06-13 16:16 UTC, patrickbrouwers requested changes
Thanks for your PR, looking good; just a few small remarks. Also please fix the failing tests.

2017-06-13 16:16 UTC, patrickbrouwers commented on config/doctrine.php
> +    'debugbar_widget_key'        => env('DOCTRINE_DEBUGBAR_KEY', 'queries'),
Don't think it's really needed to have a env variable for this. You would change this setting for your project, not per environment.

2017-06-13 16:16 UTC, patrickbrouwers commented on src/Loggers/Debugbar/DoctrineCollector.php
> +     * DoctrineCollector constructor.
Ommit description

2017-06-13 16:16 UTC, patrickbrouwers commented on src/Loggers/Debugbar/DoctrineCollector.php
> +    protected $name;
I would prefer `widgetName` as that would be more explicit.

2017-06-13 16:16 UTC, patrickbrouwers commented on config/doctrine.php
> +    'debugbar_widget_key'        => env('DOCTRINE_DEBUGBAR_KEY', 'queries'),
Also think this should be `debugbar_widget_name`.

2017-06-19 14:54 UTC, zquintana commented on config/doctrine.php
> +    'debugbar_widget_key'        => env('DOCTRINE_DEBUGBAR_KEY', 'queries'),
Changed it to `debugbar_widget_name` in latest commit.

2017-06-19 14:54 UTC, zquintana commented on src/Loggers/Debugbar/DoctrineCollector.php
> +     * DoctrineCollector constructor.
Removed the description too.

2017-06-21 20:37 UTC, patrickbrouwers requested changes
Please fix tests + code-style issue. (See merge checks)

2018-02-27 12:43 UTC, patrickbrouwers commented
Replaced

2018-02-27 12:43 UTC, closed without merging