[FIX] Depend on AbstractQuery instead of Query
laravel-doctrine/orm pull request #301
Opened 2018-01-29 10:02 UTC by bjdelange

### Changes proposed in this pull request:
- fix two method parameters to require AbstractQuery instead of Query (which is final) so it can be used with mocks for testing

2018-02-27 12:19 UTC, patrickbrouwers requested changes

2018-02-27 12:19 UTC, patrickbrouwers commented on src/Pagination/PaginatesFromParams.php
> +    public function paginate(AbstractQuery $query, $perPage, $page = 1, $fetchJoinCollection = true)
AbstractQuery is not imported. Did you test this?

2018-03-07 12:59 UTC, bjdelange commented on src/Pagination/PaginatesFromParams.php
> +    public function paginate(AbstractQuery $query, $perPage, $page = 1, $fetchJoinCollection = true)
Oops.. copy paste mistake. I found this one just as I was reviewing so it was a last minute change.

2018-03-07 20:21 UTC, patrickbrouwers approved these changes

2018-03-07 20:21 UTC, merged