[FEATURE] Allow Lumen Publishing
laravel-doctrine/orm pull request #307
Opened 2018-02-12 16:45 UTC by ragboyjr

### Changes proposed in this pull request:

- Allows for publishing config files in lumen.

Even though lumen doesn't provide vendor publishing by default, it's easily enabled by just adding in the `Illuminate\Foundation\Console\VendorPublishCommand`. However, since you have the `isLumen` check, no laravel-doctrine files get published.

2018-02-15 04:45 UTC, ragboyjr commented
ping

2018-02-22 03:19 UTC, ragboyjr commented
ping

2018-02-27 12:21 UTC, patrickbrouwers requested changes

2018-02-27 12:21 UTC, patrickbrouwers commented on src/DoctrineServiceProvider.php
> +            $this->getConfigPath() => config_path('doctrine.php'),
Clean lumen install doesn't have a config_path helper.

2018-02-27 15:06 UTC, closed without merging

2018-02-27 15:09 UTC, ragboyjr commented
@patrickbrouwers didn't mean to annoy you. I get a flood of emails every day it feels like, sometimes, I see a Github notification but then forget about it that day.

I'm closing this because the laravel foundation/helpers conflict with the lumen helpers. When I first tried this, the lumen helpers loaded first, but when used composer install from a fresh install, laravel's went first and it broke the system. So unfortunately you can't have laravel/framework installed with lumen :(.

Thank you by the way for taking the time to make this package and review the code. It's been very helpful in my projects.